### ISSUE TITLE
networkx error

### ISSUE THREAD

**Issue by prabhatM** [eugenejw/WordSegmentation#1]
hi,
even while trying a toy example I get networkx error - "networkx has no attribute 'connected_component_subgraph.

Regards

Prabhat

**Comment by engineerjoe440** [comment]
I have also seen this error. Just found a similar issue posted for a different Python Module with NetworkX as a dependency: https://github.com/rkistner/chinese-postman/issues/21

Here's my specific traceback:
```
Python 3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019, 22:39:24) [MSC v.1916 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from wordsegmentation import WordSegment
>>> ws = WordSegment()
>>> ws.segment('universityofwashington')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\joestan\AppData\Local\Programs\Python\Python38-32\lib\site-packages\wordsegmentation.py", line 553, in segment
    components = self._find_components(meaningful_words)
  File "C:\Users\joestan\AppData\Local\Programs\Python\Python38-32\lib\site-packages\wordsegmentation.py", line 322, in _find_components
    components = list(nx.connected_component_subgraphs(component_graph))
AttributeError: module 'networkx' has no attribute 'connected_component_subgraphs'
>>>

```

Seems the resolution is also shown in that response: https://github.com/rkistner/chinese-postman/issues/21#issuecomment-568980233
> ` def connected_component_subgraphs(G):`
> `    for c in nx.connected_components(G):`
>  `       yield G.subgraph(c)`

**Comment by ShurayukiHime** [comment]
Hi there,
I also have the same issue:
```
<ipython-input-6-96881fb058c4> in <module>
     10         excluded_bc_tooshort.add(text)
     11         continue
---> 12     segments = ws.segment(text)
     13     print(text)
     14     print(segments)

/usr/local/lib/python3.6/dist-packages/wordsegmentation.py in segment(self, text)
    551         #find components from the original input string
    552         components = []
--> 553         components = self._find_components(meaningful_words)
    554 
    555         post_components = []

/usr/local/lib/python3.6/dist-packages/wordsegmentation.py in _find_components(self, meaningful_words)
    320         component_graph = self._init_graph(meaningful_words)
    321         components = []
--> 322         components = list(nx.connected_component_subgraphs(component_graph))
    323         return components
    324 

AttributeError: module 'networkx' has no attribute 'connected_component_subgraphs'
```

and unfortunately the above solution did not work for me because

```
/home/USER/WordSegmentation/wordsegmentation.py in segment(self, text)
    555         post_components = []
    556         for each in components:
--> 557             post_components.append(self._opt_component(each))
    558         #print "{}components found".format(len(post_components)
    559         #print "post_components is {}".format(post_components)

/home/USER/WordSegmentation/wordsegmentation.py in _opt_component(self, component)
    351         #the sorted list is [((1, 4), 'ace', -4.964005188761728), ((0, 4), 'face', -4.0926128161036965), ((4, 6), 'bo', -5.2144070696039995), ((4, 7), 'boo', -5.550655106498099), ((4, 8), 'book', -3.490909555336102), ((0, 8), 'facebook', -6.671146108616224)]
    352         meaningful_words = component.nodes()
--> 353         meaningful_words.sort(key=lambda x: x[0][1])
    354         #print "old meaningful list is {}".format(meaningful_words)
    355         old_meaningful_words = copy.deepcopy(meaningful_words)

AttributeError: 'NodeView' object has no attribute 'sort'
```
